# Generated by Django 3.2.15 on 2023-03-22 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_name', models.CharField(max_length=255)),
                ('line_name', models.CharField(max_length=255)),
                ('machine_name', models.CharField(max_length=255)),
                ('datetime', models.DateTimeField()),
                ('error_code', models.CharField(max_length=255)),
                ('error_message', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_name', models.CharField(max_length=255)),
                ('line_name', models.CharField(max_length=255)),
                ('machine_name', models.CharField(max_length=255)),
                ('tag_name', models.CharField(max_length=255)),
                ('tag_id', models.CharField(max_length=255)),
                ('register', models.CharField(max_length=255)),
                ('data_type', models.CharField(choices=[('BIT', 'BIT'), ('STRING', 'STRING'), ('STATUS', 'STATUS'), ('ERROR CODE', 'ERROR CODE')], max_length=255)),
                ('display', models.CharField(choices=[('BUTTON', 'BUTTON'), ('INDICATOR', 'INDICATOR'), ('TEXT', 'TEXT'), ('NUMBER', 'NUMBER')], max_length=255)),
                ('color', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LineRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_name', models.CharField(max_length=255)),
                ('line_name', models.CharField(max_length=255)),
                ('deviceId', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('deviceName', models.CharField(max_length=255)),
                ('number', models.IntegerField()),
                ('status', models.CharField(max_length=255)),
                ('ip_camera', models.CharField(blank=True, max_length=255)),
                ('picturePath', models.ImageField(blank=True, upload_to='images/')),
                ('guid', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('remote_host', models.CharField(default='hostname', max_length=255)),
                ('remote_password', models.CharField(default='12345678', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PlantInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('detail', models.CharField(max_length=255)),
                ('ip1', models.CharField(max_length=255)),
                ('port1', models.CharField(max_length=255)),
                ('ip2', models.CharField(blank=True, max_length=255)),
                ('port2', models.CharField(blank=True, max_length=255)),
                ('ip3', models.CharField(blank=True, max_length=255)),
                ('port3', models.CharField(blank=True, max_length=255)),
                ('ip4', models.CharField(blank=True, max_length=255)),
                ('port4', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TimeLineStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_name', models.CharField(max_length=255)),
                ('line_name', models.CharField(max_length=255)),
                ('machine_name', models.CharField(max_length=255)),
                ('datetime', models.DateTimeField()),
                ('status', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ErrorNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_code', models.CharField(max_length=255)),
                ('error_message', models.CharField(max_length=255)),
                ('tag_member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.indicator')),
            ],
        ),
    ]
