# Generated by Django 3.2.15 on 2023-03-23 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelinestatus',
            name='error_code',
            field=models.CharField(default='0', max_length=255),
            preserve_default=False,
        ),
    ]
