# Generated by Django 3.2.15 on 2023-01-18 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceId', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('deviceName', models.CharField(max_length=255)),
                ('picturePath', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
