# Generated by Django 3.2.15 on 2023-03-28 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_timelinestatus_error_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeLineStartEnd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField()),
                ('end', models.DateField()),
            ],
        ),
    ]
