# Generated by Django 3.2.15 on 2023-01-09 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_plantinfo_detail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plantinfo',
            old_name='ip',
            new_name='ip1',
        ),
        migrations.RenameField(
            model_name='plantinfo',
            old_name='port',
            new_name='port1',
        ),
        migrations.AddField(
            model_name='plantinfo',
            name='ip2',
            field=models.CharField(blank=True, default='null', max_length=255),
        ),
        migrations.AddField(
            model_name='plantinfo',
            name='ip3',
            field=models.CharField(blank=True, default='null', max_length=255),
        ),
        migrations.AddField(
            model_name='plantinfo',
            name='ip4',
            field=models.CharField(blank=True, default='null', max_length=255),
        ),
        migrations.AddField(
            model_name='plantinfo',
            name='port2',
            field=models.CharField(blank=True, default='null', max_length=255),
        ),
        migrations.AddField(
            model_name='plantinfo',
            name='port3',
            field=models.CharField(blank=True, default='null', max_length=255),
        ),
        migrations.AddField(
            model_name='plantinfo',
            name='port4',
            field=models.CharField(blank=True, default='null', max_length=255),
        ),
    ]
