# Generated by Django 3.2.15 on 2023-01-09 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20230109_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantinfo',
            name='ip2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='plantinfo',
            name='ip3',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='plantinfo',
            name='ip4',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='plantinfo',
            name='port2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='plantinfo',
            name='port3',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='plantinfo',
            name='port4',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
