# Generated by Django 3.2.15 on 2023-01-20 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20230118_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linerow',
            name='picturePath',
            field=models.ImageField(default='app/static/default.png', upload_to='images/'),
        ),
    ]
