# Generated by Django 3.2.15 on 2023-01-20 10:05

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_linerow_picturepath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linerow',
            name='picturePath',
            field=models.ImageField(default=app.models.default_image_path, upload_to='images/'),
        ),
    ]
