# Generated by Django 3.2.15 on 2023-01-24 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_linerow_picturepath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linerow',
            name='number',
            field=models.IntegerField(unique=True),
        ),
    ]
