# Generated by Django 3.2.15 on 2023-03-29 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20230329_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='errortype',
            name='comment',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
