# Generated by Django 3.2.15 on 2023-01-24 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_linerow_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='linerow',
            name='status',
            field=models.CharField(default='0', max_length=255),
            preserve_default=False,
        ),
    ]
