# Generated by Django 3.2.15 on 2023-01-25 06:49

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_linerow_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linerow',
            name='picturePath',
        ),
        migrations.CreateModel(
            name='MachineInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=255)),
                ('machine_no', models.CharField(max_length=255)),
                ('machine_name', models.CharField(max_length=255)),
                ('ip_camera', models.CharField(max_length=255)),
                ('picturePath', models.ImageField(default=app.models.default_image_path, upload_to='images/')),
                ('Plant_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.plantinfo')),
            ],
        ),
    ]
