# Generated by Django 3.2.15 on 2023-04-17 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_utilizationrateperday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilizationrateperday',
            name='datetime',
            field=models.DateField(),
        ),
    ]
