# Generated by Django 3.2.15 on 2023-01-25 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20230125_1349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machineinfo',
            old_name='device_name',
            new_name='deviceId',
        ),
        migrations.RenameField(
            model_name='machineinfo',
            old_name='machine_name',
            new_name='deviceName',
        ),
        migrations.RenameField(
            model_name='machineinfo',
            old_name='machine_no',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='machineinfo',
            old_name='Plant_name',
            new_name='plant_name',
        ),
    ]
