# Generated by Django 3.2.15 on 2023-04-17 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_utilizationrateperday_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilizationrateperday',
            name='datetime',
            field=models.DateTimeField(),
        ),
    ]
