# Generated by Django 3.2.15 on 2023-01-25 07:06

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20230125_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='linerow',
            name='ip_camera',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='linerow',
            name='picturePath',
            field=models.ImageField(default=app.models.default_image_path, upload_to='images/'),
        ),
        migrations.DeleteModel(
            name='MachineInfo',
        ),
    ]
