# Generated by Django 3.2.15 on 2023-01-25 08:59

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_linerow_plant_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linerow',
            name='picturePath',
            field=models.ImageField(blank=True, default=app.models.default_image_path, null=True, upload_to='images/'),
        ),
    ]
