# Generated by Django 3.2.15 on 2023-04-17 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20230417_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinemembers',
            name='plant_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.plantinfo'),
        ),
    ]
