# Generated by Django 3.2.15 on 2023-04-17 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_machinemembers_plant_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinemembers',
            name='plant_name',
            field=models.CharField(max_length=255),
        ),
    ]
