# Generated by Django 3.2.15 on 2023-01-25 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_linerow_picturepath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linerow',
            name='number',
            field=models.IntegerField(),
        ),
    ]
