# Generated by Django 3.2.15 on 2023-01-25 10:03

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_linerow_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linerow',
            name='number',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='linerow',
            name='picturePath',
            field=models.ImageField(default=app.models.default_image_path, upload_to='images/'),
        ),
    ]
