# Generated by Django 3.2.15 on 2023-04-17 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_machinemembers_plant_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machinemembers',
            old_name='plant_name',
            new_name='plantInfo',
        ),
    ]
