# Generated by Django 3.2.15 on 2023-04-17 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_rename_plant_name_machinemembers_plantinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timelinestatus',
            name='line_name',
        ),
        migrations.RemoveField(
            model_name='timelinestatus',
            name='machine_name',
        ),
        migrations.RemoveField(
            model_name='timelinestatus',
            name='plant_name',
        ),
        migrations.AddField(
            model_name='timelinestatus',
            name='machineInfo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.machinemembers'),
        ),
    ]
