# Generated by Django 3.2.15 on 2023-01-27 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20230126_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linerow',
            name='number',
            field=models.IntegerField(),
        ),
    ]
