# Generated by Django 3.2.15 on 2023-01-30 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_linerow_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_name', models.CharField(max_length=255)),
                ('line_name', models.CharField(max_length=255)),
                ('machine_name', models.CharField(max_length=255)),
                ('tag_name', models.CharField(max_length=255)),
                ('tag_id', models.CharField(max_length=255)),
                ('register', models.CharField(max_length=255)),
                ('data_type', models.CharField(choices=[('BIT', 'BIT'), ('STRING', 'STRING'), ('STATUS', 'STATUS'), ('ERROR CODE', 'ERROR CODE')], max_length=255)),
                ('display', models.CharField(choices=[('BUTTON', 'BUTTON'), ('INDICATOR', 'INDICATOR'), ('TEXT', 'TEXT'), ('NUMBER', 'NUMBER')], max_length=255)),
                ('color', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
