# Generated by Django 3.2.15 on 2023-04-18 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20230417_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='errorhistory',
            name='line_name',
        ),
        migrations.RemoveField(
            model_name='errorhistory',
            name='machine_name',
        ),
        migrations.RemoveField(
            model_name='errorhistory',
            name='plant_name',
        ),
        migrations.AddField(
            model_name='errorhistory',
            name='machineInfo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.machinemembers'),
        ),
        migrations.AlterField(
            model_name='errorhistory',
            name='error_message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='error_msg', to='app.errormessage'),
        ),
        migrations.DeleteModel(
            name='ErrorNotification',
        ),
    ]
