# Generated by Django 3.2.15 on 2023-04-19 04:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_rename_machine_type_errormessage_error_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilizationrateperday',
            name='rate',
            field=models.FloatField(validators=[django.core.validators.DecimalValidator(decimal_places=2, max_digits=3)]),
        ),
        migrations.AlterField(
            model_name='utilizationrateperhour',
            name='rate',
            field=models.FloatField(validators=[django.core.validators.DecimalValidator(decimal_places=2, max_digits=3)]),
        ),
    ]
