# Generated by Django 3.2.15 on 2023-02-01 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_errornotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linerow',
            name='picturePath',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
