# Generated by Django 3.2.15 on 2023-03-02 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_linerow_picturepath'),
    ]

    operations = [
        migrations.AddField(
            model_name='linerow',
            name='remote_host',
            field=models.CharField(default='0.0.0.0', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='linerow',
            name='remote_password',
            field=models.CharField(default='12345678', max_length=255),
            preserve_default=False,
        ),
    ]
