# Generated by Django 3.2.15 on 2023-04-19 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20230419_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilizationrateperday',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='utilizationrateperhour',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
