# Generated by Django 3.2.15 on 2023-04-25 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20230419_1110'),
    ]

    operations = [
        migrations.CreateModel(
            name='TBS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetimeStart', models.DateTimeField()),
                ('datetimeEnd', models.DateTimeField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('duration', models.TimeField()),
                ('machineInfo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.machinemembers')),
            ],
        ),
    ]
