# Generated by Django 3.2.15 on 2023-03-14 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20230314_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='errorcounting',
            name='line_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='errorcounting',
            name='machine_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='errorcounting',
            name='plant_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
