# Generated by Django 3.2.15 on 2023-04-25 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_tbs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbs',
            name='duration',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tbs',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
