# Generated by Django 3.2.15 on 2023-03-16 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20230314_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeLineStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_name', models.CharField(max_length=255)),
                ('line_name', models.CharField(max_length=255)),
                ('machine_name', models.CharField(max_length=255)),
                ('data_date', models.DateField()),
                ('data_time', models.TimeField()),
                ('status', models.CharField(max_length=255)),
            ],
        ),
    ]
