# Generated by Django 3.2.15 on 2023-03-20 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_rename_data_time_errorcounting_datetime'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ErrorCounting',
            new_name='ErrorHistory',
        ),
    ]
